env:
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - standard
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
ignorePatterns:
  - 'node_modules'
  - 'dist'
  - 'legacy'
rules: {}
settings:
  react:
    version: 'detect'
