name: BUILD

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    uses: ctrlaltdev/resume/.github/workflows/lint.yml@main

  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs:
      - lint

    steps:
    - uses: actions/checkout@v2

    - run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_ENV
    
    - name: Use Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Install dependencies
      run: npm ci --ignore-scripts --omit=dev

    - name: Build
      run: npm run build
    
    - name: setup git config
      run: |
        git config user.name "GitHub Actions"
        git config user.email "<>"

    - name: commit
      run: |
        git add docs/resume.pdf
        git commit -m "build: update resume.pdf"
        git push origin main